GeneralSQL/Error.py,sha256=kBrYZ17K0Jps9-DY3QFG_tLa9GOrLBJvoTLv8wwxfMk,2321
GeneralSQL/__init__.py,sha256=zBEGFyhmEiSisj9DPgqs8qpC23Z5ksfnSjIVPpzHSQA,2155
GeneralSQL/Template/__init__.py,sha256=aMLYhiVXIFE5Hw9qlL10VX5caadJcWZHXUiZh3H1FIM,1435
GeneralSQL/Template/base.py,sha256=eQps_95SA2x7mI-LAeiRgFozkQ2TeOW1k6v2vIqOsHs,3023
GeneralSQL/db/Jmysql.py,sha256=xezdHKHslk23SptFgih4-Z5yGXmgbLCcPrhYdqjG0sU,14668
GeneralSQL/db/__init__.py,sha256=PgWm-6m5ZDVt2vjNOtrgO7sQYzXa6A0p8Y2RnoZNTl0,57
GeneralSQL-1.0.2.dist-info/LICENSE,sha256=OXLcl0T2SZ8Pmy2_dmlvKuetivmyPd5m1q-Gyd-zaYY,35149
GeneralSQL-1.0.2.dist-info/METADATA,sha256=uaSfKqEoD3Rz3jWLe5NDxZpZG1QFn0q84_0aUWjxDrE,3487
GeneralSQL-1.0.2.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
GeneralSQL-1.0.2.dist-info/top_level.txt,sha256=N28y8Tp5KNt4vFIdlg6UXzrY9QGtXwgK-oqRvdRBuh8,11
GeneralSQL-1.0.2.dist-info/RECORD,,
